local T = require "harness"
local utf8 = require "core.text.utf8"

local FFFD = "\239\191\189" 

local function collect(s)
  local out = {}
  for c in utf8.chars(s) do out[#out + 1] = c end
  return out
end

T.eq(utf8.len("hello"), 5, "ascii len")
T.eq(utf8.len(""), 0, "empty len")
T.eq(utf8.len("سلام"), 4, "persian len (all 2-byte)")
T.eq(utf8.len("خ"), 1, "2-byte U+062E")
T.eq(utf8.len("€"), 1, "3-byte U+20AC")
T.eq(utf8.len("🎵"), 1, "4-byte U+1F3B5")
T.eq(utf8.len("aخ€🎵b"), 5, "mixed ascii/2/3/4-byte len")
T.eq(utf8.len("\0"), 1, "NUL counts as a char")
T.eq(utf8.len(nil), 0, "nil-safe len")
T.eq(utf8.len(42), 0, "non-string len")

T.eq(collect("a"), { "a" }, "chars ascii")
T.eq(collect("خ€🎵"), { "خ", "€", "🎵" }, "chars 2/3/4-byte")
T.eq(collect("aسلامb"), { "a", "س", "ل", "ا", "م", "b" }, "chars mixed latin+persian")
T.eq(collect(""), {}, "chars empty")
T.eq(collect(nil), {}, "chars nil-safe")

T.eq(utf8.offset("abc", 1), 1, "offset first")
T.eq(utf8.offset("abc", 3), 3, "offset third")
T.eq(utf8.offset("abc", 4), nil, "offset past end")
T.eq(utf8.offset("خx", 2), 3, "offset after 2-byte char")
T.eq(utf8.offset("€x", 2), 4, "offset after 3-byte char")
T.eq(utf8.offset("🎵x", 2), 5, "offset after 4-byte char")
T.eq(utf8.offset("", 1), nil, "offset empty")
T.eq(utf8.offset("abc", 0), nil, "offset n < 1")
T.eq(utf8.offset(nil, 1), nil, "offset nil-safe")

T.eq(utf8.sanitize("hello سلام"), "hello سلام", "valid text unchanged")
T.eq(utf8.sanitize("خ€🎵"), "خ€🎵", "valid 2/3/4-byte unchanged")
T.eq(utf8.sanitize(""), "", "sanitize empty")
T.eq(utf8.sanitize(nil), "", "sanitize nil-safe")
T.eq(utf8.sanitize("\0"), "\0", "NUL passes through")
T.eq(utf8.sanitize("\128"), FFFD, "lone continuation 0x80")
T.eq(utf8.sanitize("a\128b"), "a" .. FFFD .. "b", "lone continuation mid-text")
T.eq(utf8.sanitize("\195"), FFFD, "truncated 2-byte lead at end")
T.eq(utf8.sanitize("\192\128"), FFFD .. FFFD, "overlong 2-byte (C0 80)")
T.eq(utf8.sanitize("\224\128\128"), FFFD .. FFFD .. FFFD, "overlong 3-byte (E0 80 80)")
T.eq(utf8.sanitize("\237\160\128"), FFFD .. FFFD .. FFFD, "UTF-16 surrogate (ED A0 80)")
T.eq(utf8.sanitize("\240\159\134"), FFFD .. FFFD .. FFFD, "truncated 4-byte at end")

local cp, pos = utf8.decode("a", 1)
T.eq(cp, 97, "decode ascii cp")
T.eq(pos, 2, "decode ascii next pos")
cp, pos = utf8.decode("خ", 1)
T.eq(cp, 0x062E, "decode U+062E")
T.eq(pos, 3, "decode 2-byte next pos")
cp, pos = utf8.decode("€", 1)
T.eq(cp, 0x20AC, "decode U+20AC")
T.eq(pos, 4, "decode 3-byte next pos")
cp, pos = utf8.decode("🎵", 1)
T.eq(cp, 0x1F3B5, "decode U+1F3B5")
T.eq(pos, 5, "decode 4-byte next pos")
cp, pos = utf8.decode("abc", 3)
T.eq(cp, 99, "decode at given pos")
T.eq(pos, 4, "next pos at given pos")
cp, pos = utf8.decode("", 1)
T.eq(cp, nil, "decode empty returns nil cp")
T.eq(pos, 1, "decode empty keeps pos")
cp, pos = utf8.decode("a", 2)
T.eq(cp, nil, "decode past end returns nil cp")
cp, pos = utf8.decode("\128", 1)
T.eq(cp, 0xFFFD, "decode invalid byte -> replacement")
T.eq(pos, 2, "decode invalid byte advances one")

T.eq(utf8.encode(0x41), "A", "encode ascii")
T.eq(utf8.encode(0x062E), "خ", "encode 2-byte")
T.eq(utf8.encode(0x20AC), "€", "encode 3-byte")
T.eq(utf8.encode(0x1F3B5), "🎵", "encode 4-byte")
T.eq(utf8.encode(), FFFD, "encode() defaults to U+FFFD")
T.eq(utf8.encode(0x110000), utf8.encode(0x10FFFF), "encode clamps > U+10FFFF")
cp, pos = utf8.decode(utf8.encode(0x1234), 1)
T.eq(cp, 0x1234, "decode(encode(x)) roundtrip")

T.ok(utf8.is_cont(0x80), "0x80 is continuation")
T.ok(utf8.is_cont(0xBF), "0xBF is continuation")
T.ok(not utf8.is_cont(0x41), "ascii is not continuation")
T.ok(not utf8.is_cont(0xC0), "lead byte is not continuation")
T.ok(not utf8.is_cont(nil), "nil-safe is_cont")
