#!/usr/bin/env python3
"""
Usage:
    python3 scripts/gen_icon.py [--svg PATH] [--out PATH]

Defaults:
    --svg  scripts/icon.svg
    --out  src/icon.inl
"""

import sys
import os
import argparse
import base64
import struct


def svg_to_ico_bytes(svg_path: str) -> bytes:
    """
    Convert SVG to a minimal ICO file (32x32 and 16x16) using only stdlib.
    Falls back to embedding SVG as raw bytes if Pillow/cairosvg not available.
    """
    try:
        from PIL import Image
        import cairosvg
        import io

        sizes = [256, 64, 48, 32, 16]
        images = []
        for size in sizes:
            png_bytes = cairosvg.svg2png(
                url=svg_path, output_width=size, output_height=size
            )
            img = Image.open(io.BytesIO(png_bytes)).convert("RGBA")
            images.append(img)

        # Build ICO manually
        num_images = len(images)
        # ICO header: 6 bytes
        # Directory entries: 16 bytes each
        # Image data follows
        header = struct.pack("<HHH", 0, 1, num_images)
        dir_entries = b""
        image_data = b""
        offset = 6 + 16 * num_images

        for img in images:
            w, h = img.size
            buf = io.BytesIO()
            img.save(buf, format="PNG")
            png = buf.getvalue()
            size_bytes = len(png)
            bw = w if w < 256 else 0
            bh = h if h < 256 else 0
            dir_entries += struct.pack(
                "<BBBBHHII", bw, bh, 0, 0, 1, 32, size_bytes, offset
            )
            image_data += png
            offset += size_bytes

        return header + dir_entries + image_data

    except ImportError:
        pass

    # Fallback: embed the raw SVG bytes (works when linked directly)
    print(
        "[gen_icon] Note: Pillow/cairosvg not found – embedding raw SVG bytes.",
        file=sys.stderr,
    )
    with open(svg_path, "rb") as f:
        return f.read()


def bytes_to_c_array(data: bytes, array_name: str = "WINDOW_ICON") -> str:
    """Convert raw bytes to a C byte-array literal."""
    lines = []
    lines.append(f"/* Auto-generated by scripts/gen_icon.py – do not edit */")
    lines.append(f"static const unsigned char {array_name}[] = {{")

    row_width = 16
    for i in range(0, len(data), row_width):
        chunk = data[i : i + row_width]
        hex_values = ", ".join(f"0x{b:02x}" for b in chunk)
        lines.append(f"    {hex_values},")

    lines.append("};")
    lines.append(f"static const unsigned int {array_name}_LEN = {len(data)}U;")
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description="Generate icon.inl from icon.svg")
    parser.add_argument(
        "--svg",
        default=os.path.join("scripts", "icon.svg"),
        help="Path to source SVG (default: scripts/icon.svg)",
    )
    parser.add_argument(
        "--out",
        default=os.path.join("src", "icon.inl"),
        help="Output .inl path (default: src/icon.inl)",
    )
    args = parser.parse_args()

    svg_path = args.svg
    out_path = args.out

    if not os.path.isfile(svg_path):
        print(f"[gen_icon] ERROR: SVG not found: {svg_path}", file=sys.stderr)
        sys.exit(1)

    print(f"[gen_icon] Reading SVG: {svg_path}")
    icon_bytes = svg_to_ico_bytes(svg_path)

    c_source = bytes_to_c_array(icon_bytes)

    out_dir = os.path.dirname(out_path)
    if out_dir:
        os.makedirs(out_dir, exist_ok=True)

    with open(out_path, "w", encoding="utf-8") as f:
        f.write(c_source)

    print(f"[gen_icon] Written {len(icon_bytes)} bytes -> {out_path}")

if __name__ == "__main__":
    main()